language: cpp

git:
  depth: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC="gcc-7"
        - CXX="g++-7"
    - os: osx
      osx_image: xcode9.2
      before_install:
        - brew update
        - brew install --overwrite gcc
      env:
        - CC="gcc-7"
        - CXX="g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - CC="clang-5.0"
        - CXX="clang++-5.0"

install:
  - ./gradlew --console=plain

script:
  - ./gradlew --console=plain assemble
  - ./gradlew --console=plain check
